// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSiwcShT1jPb1MUJqQWO4hDgH3vHp-G4E',
    appId: '1:799474834220:web:9ae480909f16caa5972a89',
    messagingSenderId: '799474834220',
    projectId: 'atmflutter',
    authDomain: 'atmflutter.firebaseapp.com',
    storageBucket: 'atmflutter.appspot.com',
    measurementId: 'G-L04MWLYKHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOTsbUhDRJJj579bLCGKGUzXGXiTnreo',
    appId: '1:799474834220:android:d26bbebd65282cb9972a89',
    messagingSenderId: '799474834220',
    projectId: 'atmflutter',
    storageBucket: 'atmflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWY6AhfUs9SvsmaoJiUG1mrqm86Dxexg4',
    appId: '1:799474834220:ios:fe4d4446f2c88989972a89',
    messagingSenderId: '799474834220',
    projectId: 'atmflutter',
    storageBucket: 'atmflutter.appspot.com',
    androidClientId: '799474834220-ojmd525o6nsfugafjdskmbgdkb0nlpls.apps.googleusercontent.com',
    iosClientId: '799474834220-l3jsthgmo7d20bq8685l01lhuaclgu6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWY6AhfUs9SvsmaoJiUG1mrqm86Dxexg4',
    appId: '1:799474834220:ios:fe4d4446f2c88989972a89',
    messagingSenderId: '799474834220',
    projectId: 'atmflutter',
    storageBucket: 'atmflutter.appspot.com',
    androidClientId: '799474834220-ojmd525o6nsfugafjdskmbgdkb0nlpls.apps.googleusercontent.com',
    iosClientId: '799474834220-l3jsthgmo7d20bq8685l01lhuaclgu6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.contacts',
  );
}
